site_name: IntraMaps Roam Docs
pages:
- [index.md, Home]
- [about.md, About]
- ['features/overview.md', 'Feature Overview']
- ['admin-guide/projectadmin.md', 'Admin Guide', 'Creating a project']
- ['admin-guide/ProjectUpdating.md', 'Admin Guide', 'Project Install/Update']
- ['admin-guide/widgetevents.md', 'Admin Guide', 'Form Events']
- ['admin-guide/widgettypes.md', 'Admin Guide', 'Widget Types']
- ['admin-guide/Info-Links.md', 'Admin Guide', 'Info Links']
- ['admin-guide/Searching.md', 'Admin Guide', 'Searching']
- ['admin-guide/Select-Config.md', 'Admin Guide', 'Select Info Config']
- ['admin-guide/Syncing.md', 'Admin Guide', 'Syncing']
- ['admin-guide/capturevalues.md', 'Admin Guide', 'Capturing other layer values']
- ['admin-guide/profiles.md', 'Admin Guide', 'Profiles']
- ['features/Features-2.5.md', 'Change Logs', '2.5']
- ['features/Features-2.4.md', 'Change Logs', '2.4']
- ['features/Features-2.3.md', 'Change Logs', '2.3']
- ['features/Features-2.2.md', 'Change Logs', '2.2']
- ['features/Features-2.1.md', 'Change Logs', '2.1']
- ['dev-guide/Building.md', 'Dev Guide', 'Building Roam']
- ['dev-guide/Plugins.md', 'Dev Guide', 'Plugins']
- ['dev-guide/formlogic.md', 'Dev Guide', 'Adding Form Logic']
- ['api/apinotes.md', 'API', 'Important API Notes']
- ['api/events.md', 'API', 'Events']
- ['api/featureform.md', 'API', 'Feature Form']
- ['titbits/usecases.md', 'Other Info', 'Users']
theme: readthedocs
