site_name: IntraMaps Roam Docs
pages:
- [index.md, Home]
- [about.md, About]
- ['admin-guide/projectadmin.md', 'Admin Guide', 'Creating a project']
- ['admin-guide/widgettypes.md', 'Admin Guide', 'Widget Types']
- ['admin-guide/Info-Links.md', 'Admin Guide', 'Info Links']
- ['admin-guide/Searching.md', 'Admin Guide', 'Searching']
- ['admin-guide/Select-Config.md', 'Admin Guide', 'Select Info Config']
- ['admin-guide/Syncing.md', 'Admin Guide', 'Syncing']
- ['dev-guide/Building.md', 'Dev Guide', 'Building Roam']
- ['dev-guide/Plugins.md', 'Dev Guide', 'Plugins']
- ['dev-guide/formlogic.md', 'Dev Guide', 'Adding Form Logic']
- ['api/events.md', 'API', 'Events']
- ['api/featureform.md', 'API', 'Feature Form']
theme: readthedocs
